---
# tasks file for ansible-homeassistant

- name: Create homeassistant user
  user: name={{ homeassistant_user }}
  become: yes

- name: install systemd file
  template: 
    src=systemd.j2
    dest=/etc/systemd/system/homeassistant.service
    mode=0755
  become: yes
  notify:
    - reload systemctl

- name: Install apt dependencies
  apt: name={{ item }} state=latest 
  become: yes
  with_items:
    - python3
    - python-virtualenv
    - git

- name: check if virtualenv exists
  stat:
    path: "{{ homeassistant_virtualenv }}/bin/python"
  register:
    stat_result

- name: create virtualenv
  command: virtualenv -p {{ homeassistant_python_executable  }}  {{ homeassistant_virtualenv }}
  become_user: "{{ homeassistant_user }}"
  become: yes
  when:
    stat_result.stat.exists == False

- name: Install homeassistant latest version
  pip:
    name: homeassistant
    executable: "{{ homeassistant_virtualenv }}/bin/pip"
  become_user: "{{ homeassistant_user }}"
  become: yes
  when: homeassistant_version == 'latest'
  notify:
    - restart homeassistant

- name: Install homeassistant version {{ homeassistant_version }}
  pip:
    name: homeassistant
    version: "{{ homeassistant_version }}"
    executable: "{{ homeassistant_virtualenv }}/bin/pip"
  become_user: "{{ homeassistant_user }}"
  become: yes
  when: homeassistant_version != 'latest'
  notify:
    - restart homeassistant

- name: install config from git
  git:
    repo: "{{ homeassistant_git_config }}"
    dest: "{{ homeassistant_config }}"
  become_user: "{{ homeassistant_user }}"
  become: yes
  when: homeassistant_git_config is defined
  notify:
    - restart homeassistant
