---
# tasks file for ansible-homeassistant

- name: Create homeassistant user
  user: name={{ homeassistant_user }}
  become: yes

- name: Install apt dependencies
  apt: name={{ item }} state=latest update_cache=yes
  become: yes
  with_items:
    - python3
    - python-virtualenv
    - git

- name: create virtualenv
  command: virtualenv -p {{ homeassistant_python_executable  }}  {{ homeassistant_virtualenv }}
  become_user: "{{ homeassistant_user }}"
  become: yes

- name: Install homeassistant latest version
  pip:
    name: homeassistant
    executable: "{{ homeassistant_virtualenv }}/bin/pip"
  become_user: "{{ homeassistant_user }}"
  become: yes
  when: homeassistant_version == 'latest'
  notify:
    - restart homeassistant

- name: Install homeassistant version {{ homeassistant_version }}
  pip:
    name: homeassistant
    version: "{{ homeassistant_version }}"
    executable: "{{ homeassistant_virtualenv }}/bin/pip"
  become_user: "{{ homeassistant_user }}"
  become: yes
  when: homeassistant_version != 'latest'
  notify:
    - restart homeassistant

- name: install upstart  file
  template:
    src=upstart.conf.j2
    dest=/etc/init/homeassistant.conf
    mode=0755
  become: yes

- name: install config from git
  git:
    repo: "{{ homeassistant_git_config }}"
    dest: "{{ homeassistant_config }}"
  become_user: "{{ homeassistant_user }}"
  become: yes
  when: homeassistant_git_config is defined
  notify:
    - restart homeassistant
