---
# tasks file for ansible-homeassistant

- name: Create homeassistant user
  user: name={{ homeassistant_user }}
  become: yes

- name: Install python virtualenv
  apt: name=python-virtualenv state=present update_cache=yes
  become: yes

- name: create virtualenv
  command: virtualenv -p python3.4 {{ homeassistant_virtualenv }}
  become_user: "{{ homeassistant_user }}"
  become: yes

- name: Install homeassistant latest version
  pip: 
    name: homeassistant
    executable: "{{ homeassistant_virtualenv }}/bin/pip"
  become_user: "{{ homeassistant_user }}"
  become: yes
 when: homeassistant_version == 'latest'
 
- name: Install homeassistant version {{ homeassistant_version }}
  pip: 
    name: homeassistant
    version: {{ homeassistant_version }}
    executable: "{{ homeassistant_virtualenv }}/bin/pip"
  become_user: "{{ homeassistant_user }}"
  become: yes
  when: homeassistant_version != 'latest'

- name: install systemd file
  template: 
    src=systemd.j2
    dest=/etc/systemd/system/homeassistant.service
    mode=0755
  when: homeassistant_systemd == 'true'
  become: yes

- name: install config from git
  git:
    repo: "{{ homeassistant_git_config }}"
    dest: "{{ homeassistant_config }}"
  when: homeassistant_git_config
  become_user: "{{ homeassistant_user }}"
  become: yes
